2020-11-10 23:08:25,362 INFO    MainThread:32104 [wandb_setup.py:_flush():68] setting env: {}
2020-11-10 23:08:25,362 INFO    MainThread:32104 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-11-10 23:08:25,362 INFO    MainThread:32104 [wandb_setup.py:_flush():68] setting login settings: {}
2020-11-10 23:08:25,362 INFO    MainThread:32104 [wandb_init.py:_log_setup():302] Logging user logs to /home/dewe/ros_ws/wandb/run-20201110_230825-2t76n863/logs/debug.log
2020-11-10 23:08:25,362 INFO    MainThread:32104 [wandb_init.py:_log_setup():303] Logging internal logs to /home/dewe/ros_ws/wandb/run-20201110_230825-2t76n863/logs/debug-internal.log
2020-11-10 23:08:26,280 INFO    MainThread:32104 [wandb_run.py:_console_start():1213] atexit reg
2020-11-10 23:08:26,280 INFO    MainThread:32104 [wandb_run.py:_redirect():1083] redirect: SettingsConsole.REDIRECT
2020-11-10 23:08:26,281 INFO    MainThread:32104 [wandb_run.py:_redirect():1086] Redirecting console.
2020-11-10 23:08:26,281 INFO    MainThread:32104 [redirect.py:install():204] install start
2020-11-10 23:08:26,281 INFO    MainThread:32104 [redirect.py:install():219] install stop
2020-11-10 23:08:26,281 INFO    MainThread:32104 [redirect.py:install():204] install start
2020-11-10 23:08:26,282 INFO    MainThread:32104 [redirect.py:install():219] install stop
2020-11-10 23:08:26,282 INFO    MainThread:32104 [wandb_run.py:_redirect():1130] Redirects installed.
2020-11-10 23:08:26,385 INFO    MainThread:32104 [wandb_setup.py:_flush():68] setting env: {}
2020-11-10 23:08:26,385 INFO    MainThread:32104 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-11-10 23:08:26,385 INFO    MainThread:32104 [wandb_setup.py:_flush():68] setting login settings: {}
2020-11-10 23:08:26,385 INFO    MainThread:32104 [wandb_init.py:_log_setup():302] Logging user logs to /home/dewe/ros_ws/wandb/run-20201110_230826-2ps2qkh5/logs/debug.log
2020-11-10 23:08:26,385 INFO    MainThread:32104 [wandb_init.py:_log_setup():303] Logging internal logs to /home/dewe/ros_ws/wandb/run-20201110_230826-2ps2qkh5/logs/debug-internal.log
2020-11-10 23:08:26,385 INFO    MainThread:32104 [wandb_init.py:init():352] wandb.init() called when a run is still active
2020-11-10 23:08:26,518 INFO    MainThread:32104 [wandb_run.py:_config_callback():545] config_cb None None {'_wandb': {'cli_version': '0.10.10', 'python_version': '3.6.12', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}, 'env': 'BaxterGym-v0', 'max_episode': 5000, 'frames': 65000, 'mem': 100000, 'per': 0, 'batch_size': 128, 'nstep': 1, 'layer_size': 150, 'gamma': 0.99, 'tau': 0.01, 'learning_rate': 0.001, 'update_every': 1, 'n_updates': 3, 'seed': 0}
2020-11-10 23:08:27,131 INFO    MainThread:32104 [wandb_run.py:_atexit_cleanup():1186] got exitcode: 1
2020-11-10 23:08:27,133 INFO    MainThread:32104 [wandb_run.py:_restore():1158] restore
2020-11-10 23:08:27,133 INFO    MainThread:32104 [redirect.py:uninstall():223] uninstall start
2020-11-10 23:08:27,133 INFO    MainThread:32104 [redirect.py:_stop():278] _stop: stdout
2020-11-10 23:08:27,134 INFO    stdout    :32104 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-11-10 23:08:27,134 INFO    MainThread:32104 [redirect.py:_stop():284] _stop closed: stdout
2020-11-10 23:08:27,134 INFO    stdout    :32104 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-11-10 23:08:27,134 INFO    MainThread:32104 [redirect.py:_stop():290] _stop joined: stdout
2020-11-10 23:08:27,135 INFO    MainThread:32104 [redirect.py:_stop():292] _stop rd closed: stdout
2020-11-10 23:08:27,135 INFO    MainThread:32104 [redirect.py:uninstall():227] uninstall done
2020-11-10 23:08:27,135 INFO    MainThread:32104 [redirect.py:uninstall():223] uninstall start
2020-11-10 23:08:27,136 INFO    MainThread:32104 [redirect.py:_stop():278] _stop: stderr
2020-11-10 23:08:27,136 INFO    MainThread:32104 [redirect.py:_stop():284] _stop closed: stderr
2020-11-10 23:08:27,136 INFO    stderr    :32104 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-11-10 23:08:27,136 INFO    stderr    :32104 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-11-10 23:08:27,137 INFO    MainThread:32104 [redirect.py:_stop():290] _stop joined: stderr
2020-11-10 23:08:27,137 INFO    MainThread:32104 [redirect.py:_stop():292] _stop rd closed: stderr
2020-11-10 23:08:27,137 INFO    MainThread:32104 [redirect.py:uninstall():227] uninstall done
2020-11-10 23:08:31,718 INFO    MainThread:32104 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "bff8d8b924a348319f3d31de13b341c1"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 775
      total_bytes: 775
    }
  }
}

2020-11-10 23:08:33,727 INFO    MainThread:32104 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "a26f03c77e3c45c48e729d9b6d344632"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 1448
      total_bytes: 7754
    }
  }
}

2020-11-10 23:08:35,732 INFO    MainThread:32104 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "3cf1f69c8e284d9ba4e2a39a386fe2e7"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 1448
      total_bytes: 7754
    }
  }
}

2020-11-10 23:08:37,740 INFO    MainThread:32104 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "0c10c274dc954298a3248e31f0b3c1ed"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 7754
      total_bytes: 7754
    }
  }
}

2020-11-10 23:08:39,743 INFO    MainThread:32104 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "9e7f87afa3e14807a481ad4dd2898942"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 7754
      total_bytes: 7754
    }
  }
}

2020-11-10 23:08:40,856 INFO    MainThread:32104 [wandb_run.py:_show_files():1509] logging synced files
2020-11-10 23:08:40,859 INFO    MainThread:32104 [internal.py:handle_exit():138] Internal process exited
